# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
