# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colap', '0002_data_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='favorite_drink',
            new_name='favourite_drink',
        ),
    ]
