# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 13:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('colap', '0003_auto_20170825_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_collector',
            field=models.CharField(default=datetime.datetime(2017, 8, 25, 13, 42, 4, 432963, tzinfo=utc), max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
