# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colap', '0004_data_data_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_collector',
            field=models.CharField(max_length=50),
        ),
    ]
